### ISSUE TITLE
console-related exception in IE11 when console is not displayed

### ISSUE THREAD

**Issue by jlowcs** [storybookjs/storybook-addon-console#11]
**Describe the bug**

On IE11, when the console is not displayed, an error is displayed with the following error:

```
TypeError: invalid calling Object
   at logger.error (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:70813:27)
   at exports.logger.error (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:74090:9)
   at showException (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:74330:3)
   at renderUI (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:74455:9)
   at emit (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:97244:15)
   at Anonymous function (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:73656:9)
   at ZoneDelegate.prototype.invokeTask (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:242597:13)
   at Zone.prototype.runTask (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:242370:21)
   at ZoneTask.invokeTask (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:242673:17)
   at invoke (http://localhost:3001/vendors~main.e923ab1e42d363b44a8b.bundle.js:242662:21)"
```

This error does not occur when the console is open.

**To Reproduce**
1. Simply start a book
2. See error

**Expected behavior**
Page should load.

**Code snippets**

`Changing` the following code in `@storybook/addon-console/dist/index.js` fixes the issue:
```javascript
var cLogger = {
  log: logger.log.bind(logger),
  warn: logger.warn.bind(logger),
  error: logger.error.bind(logger)
};
```

**System:**
 - OS: Windows10
 - Device: PC
 - Browser: IE11
 - Framework: Angular
 - Version: 1.1.0

**Comment by UsulPro** [comment]
released
