### ISSUE TITLE
[Bug] Errors when running on storybook 6

### ISSUE THREAD

**Issue by SimeonC** [storybookjs/storybook-addon-console#41]
### Describe the bug

If I add this addon to my storybook v6, it throws an error and storybook doesn't start-up.

### Steps to reproduce the behavior

1. Setup Storybook v6
2. Set the addons to `addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-console'],`
3. Run `start-storybook`
4. Error

### Expected behavior

Shouldn't error.

### Screenshots and/or logs

```
ERR! Error: Accessing non-existent addons channel, see https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel
ERR!     at AddonStore.getChannel (/Users/simeon.cheeseman/Development/settings-frontend/node_modules/@storybook/addons/dist/index.js:53:13)
ERR!     at Object.actionHandler [as log] (/Users/simeon.cheeseman/Development/settings-frontend/node_modules/@storybook/addon-actions/dist/preview/action.js:23:34)
ERR!     at console.logger.log (/Users/simeon.cheeseman/Development/settings-frontend/node_modules/@storybook/addon-console/dist/index.js:113:37)
ERR!     at outputStartupInformation (/Users/simeon.cheeseman/Development/settings-frontend/node_modules/@storybook/core/dist/server/build-dev.js:253:11)
ERR!     at buildDevStandalone (/Users/simeon.cheeseman/Development/settings-frontend/node_modules/@storybook/core/dist/server/build-dev.js:333:5)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

### Environment

 - OS: OSX 11.2.2
 - Node.js version: 15.9.0
 - NPM version: 7.5.3

**Comment by Anne-Gaelle-S** [comment]
I have the same error, but in a different context. I can't install `storybook-addon-console` because of "Accessing non-existent addons channel".

I'm running storybook with ember. 
- ember-cli: 3.25.2
- node: 14.16.0
- os: darwin x64

**Comment by BryanAdamss** [comment]
Just add below line to the `preview.js`
`import '@storybook/addon-console'`

Its work for me😂

**Comment by zhangyu1818** [comment]
Don't put `@storybook/addon-actions` into addons array, just create `preview.js` and import it.
It's work for me (storybook v6.2.9).
```javascript
// .storybook/main.js
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials'
  ],
```

```javascript
// .storybook/preview.js
import '@storybook/addon-console';
```

**Comment by Todilo** [comment]
> Don't put `@storybook/addon-actions` into addons array, just create `preview.js` and import it. It's work for me (storybook v6.2.9).
> 
> ```js
> // .storybook/main.js
>   addons: [
>     '@storybook/addon-links',
>     '@storybook/addon-essentials'
>   ],
> ```
> 
> ```js
> // .storybook/preview.js
> import '@storybook/addon-console';
> ```

this won't work for newer storybook will it? uses module.export so 

import '@storybook/addon-console';
is not valid.

**Comment by jonkers3** [comment]
@Todilo @BryanAdamss 

Any tips on why this works for you? I just get an error about using import outside of modules like the other person mentioned. 

`> Executing task: npm run storybook <

> next-boilerplate@1.0.0 storybook
> start-storybook -p 6006 -s ./public

info @storybook/react v6.5.9
(node:20368) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
ERR! C:\Web\ems-next-3-sb\.storybook\main.js:4
ERR! import '@storybook/addon-console'
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module`
