### ISSUE TITLE
[Bug] Runtime error after updating to Storybook 7.6.0

### ISSUE THREAD

**Issue by dkimmich-onventis** [storybookjs/storybook-addon-console#80]
### Describe the bug

After updating to Storybook v7.6.0, there is a runtime error in Storybook when using the addon.

### Steps to reproduce the behavior

1. Setup addon in a Storybook v7.6.0 project
2. Serve the project

https://stackblitz.com/edit/github-3rpmxh?file=.storybook%2Fpreview.ts

### Expected behavior

The app runs

### Screenshots and/or logs

There is a runtime error:

```
Error: Cannot find module '@storybook/global'
    at webpackEmptyContext (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/main.iframe.bundle.js:155:10)
    at ../../lib/channels/dist/index.js (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/vendors-node_modules_storybook_addon-console_dist_index_js-node_modules_storybook_addon-docs_-74e763.iframe.bundle.js:91935:26)
    at https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/vendors-node_modules_storybook_addon-console_dist_index_js-node_modules_storybook_addon-docs_-74e763.iframe.bundle.js:87989:50
    at ./node_modules/@storybook/addon-actions/dist/index.js (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/vendors-node_modules_storybook_addon-console_dist_index_js-node_modules_storybook_addon-docs_-74e763.iframe.bundle.js:94527:31)
    at __webpack_require__ (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/runtime~main.iframe.bundle.js:28:33)
    at fn (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/runtime~main.iframe.bundle.js:353:21)
    at ./node_modules/@storybook/addon-console/dist/index.js (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/vendors-node_modules_storybook_addon-console_dist_index_js-node_modules_storybook_addon-docs_-74e763.iframe.bundle.js:97953:21)
    at __webpack_require__ (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/runtime~main.iframe.bundle.js:28:33)
    at fn (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/runtime~main.iframe.bundle.js:353:21)
    at ./.storybook/preview.ts (https://github3rpmxh-dy3t--6006--6843a59c.local-corp.webcontainer.io/main.iframe.bundle.js:16:82)
```

### Environment

 - OS: any
 - Node.js version: LTS
 - NPM version: 10

**Comment by neviaumi** [comment]
Encountered  exact same error , did we have any update ? 

`@storybook/global`

**Comment by ndelangen** [comment]
If I remove add-console from the repro, it works:
https://stackblitz.com/edit/github-3rpmxh-jh3opr?file=package.json,.storybook%2Fpreview.ts

**Comment by dkimmich-onventis** [comment]
@ndelangen That's why the issue seems to be related to this add-on.

**Comment by dkimmich-onventis** [comment]
With v3.0.0, the issue is fixed.
